#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${file("~/.ssh/id_rsa.pub")}
  - name: jenkins
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${file("~/.ssh/jenk.pub")}
package_update: false
package_upgrade: false
packages:
  - nginx
  - mc
final_message:
  - "Container initialisation complete."