{
 "title": "TEST",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"})",
     "legendFormat": "RAM free"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})",
     "legendFormat": "MemAvial"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})",
     "legendFormat": "MemTotal"
    }
   ]
  },
  {
   "title": "CPUla1",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_load1[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "DISK SPASE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "100-(100-((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "CPUla5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPUla15",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))"
    }
   ]
  }
 ]
}