pipeline {
  environment {
    dockerimagename = "sergo2211/app"
    dockerImage = ""
    
  }
  agent any
  stages {
    stage('Checkout Source') {
      steps {
        git branch: 'main', url: 'https://github.com/Serg2211/app.git'
      }
    }

    stage('Tag') {
      steps{
        script {
          sh 'git fetch'
          gitTag=sh(returnStdout:  true, script: "git tag --sort=-creatordate | head -n 1").trim()
          echo "gitTag output: ${gitTag}"
        }
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }
    
    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhub-credentials'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("${gitTag}")
          }
        }
      }
    }

    stage('Change TAG in deploy.yaml') {
      environment {
              envTag = ("${gitTag}")
           }    
      steps{
        script {
          sh "sed -i \'18,22 s/TAG/\'$envTag\'/g\' deploy.yaml"
          sh 'cat deploy.yaml'
        }
      }
    }

  }

    
}    
node {
  stage('Deploying app to k8s') {
    withKubeConfig([credentialsId: 'k8s-credentials', serverUrl: 'https://158.160.36.239:6443']) {
      sh 'kubectl apply -f deploy.yaml'
    }
  }
}